#!/bin/bash

# Copyright (C) 2012 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.

NXAPP=nxproxy
NX_LIBS=/usr/lib/nx
NX_LOCAL_LIBS=/usr/local/lib/nx

# make sure nxagent starts properly with pam_tmpdir.so being in use
NX_TEMP=${NX_TEMP:-/tmp}
export NX_TEMP

LD_LIBRARY_PATH=$NX_LOCAL_LIBS:$NX_LOCAL_LIBS/X11:$NX_LIBS:$NX_LIBS/X11:$LD_LIBRARY_PATH
test -x $NX_LOCAL_LIBS/bin/$NXAPP && export NX_LIBS=$NX_LOCAL_LIBS
test -x $NX_LIBS/bin/$NXAPP && export NX_LIBS=$NX_LIBS

export LD_LIBRARY_PATH

exec $NX_LIBS/bin/$NXAPP "$@"