LIBRARY DRI
VERSION LIBRARY_VERSION
EXPORTS

XFree86DRIExtensionInit
DRIAuthConnection
DRIBlockHandler
DRIClipNotify
DRICloseConnection
DRICloseScreen
DRIContextPrivDelete
DRICopyWindow
DRICreateContext
DRICreateContextPriv
DRICreateContextPrivFromHandle
DRICreateDrawable
DRICreateInfoRec
DRIDestroyContext
DRIDestroyContextPriv
DRIDestroyDrawable
DRIDestroyInfoRec
DRIDoBlockHandler
DRIDoWakeupHandler
DRIDrawablePrivDelete
DRIExtensionInit
DRIFinishScreenInit
DRIGetClientDriverName
DRIGetContext
DRIGetContextStore
DRIGetDeviceInfo
DRIGetDrawableIndex
DRIGetDrawableInfo
DRIGetDrawableStamp
DRIGetSAREAPrivate
DRIGetWrappedFuncs
DRILock
DRIOpenConnection
DRIPaintWindow
DRIPostValidateTree
DRIPrintDrawableLock
DRIQueryDirectRenderingCapable
DRIQueryVersion
DRIReset
DRIScreenInit
DRISwapContext
DRIUnlock
DRIValidateTree
DRIWakeupHandler

/* $XFree86$ */
